from typing import Annotated, Optional

from langgraph.graph import MessagesState
from typing_extensions import TypedDict


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    aggressive_history: Annotated[
        str, "Aggressive Agent's Conversation history"
    ]  # Conversation history
    conservative_history: Annotated[
        str, "Conservative Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_aggressive_response: Annotated[
        str, "Latest response by the aggressive analyst"
    ]  # Last response
    current_conservative_response: Annotated[
        str, "Latest response by the conservative analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    asset_type: Annotated[str, "Asset type under analysis such as stock or crypto"]
    instrument_context: Annotated[str, "Deterministic ticker identity resolved at run start"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Sentiment Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # Structured fields from the Trader's typed output (schemas.TraderProposal),
    # populated only when the structured call succeeded — None on free-text
    # fallback. Lets downstream code (e.g. the worker computing real S/R-based
    # trade levels) know the transaction direction and the Trader's own opinion
    # on entry/stop without re-parsing trader_investment_plan's markdown.
    trader_action:      Annotated[Optional[str],   "Buy / Hold / Sell, if determinable"]
    trader_entry_price: Annotated[Optional[float], "Trader's stated entry price, if given"]
    trader_stop_loss:   Annotated[Optional[float], "Trader's stated stop-loss, if given"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
    past_context: Annotated[str, "Memory log context injected at run start (same-ticker decisions + cross-ticker lessons)"]

    # Structured fields from the Portfolio Manager's typed output (schemas.PortfolioDecision),
    # populated only when the structured call succeeded — None on free-text fallback. Kept as
    # flat, plain-typed state keys (rather than the Pydantic object itself) so downstream
    # consumers get real typed values without depending on the schemas module or re-parsing
    # final_trade_decision's markdown.
    confidence_score: Annotated[Optional[int], "Portfolio Manager's confidence 0-100, if determinable"]
    time_horizon: Annotated[Optional[str], "Recommended holding-period bucket, if determinable"]
    bullish_scenario: Annotated[Optional[str], "What has to go right for the bullish case"]
    bearish_scenario: Annotated[Optional[str], "What would invalidate the thesis"]
    key_risks: Annotated[Optional[list], "Concrete risks to the position, as short bullet strings"]
